server:
  servlet:
    context-path: /parttimes
  port: 8083

spring:
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/richdata?characterEncoding=utf-8&serverTimezone=GMT%2b8&useSSL=false
  jpa:
    show-sql: true
  #thymeleaf配置
  thymeleaf:
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/templates/
    mode: HTML5
    suffix: .html
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 127.0.0.1
    port: 6379

#日志配置
logging:
  level:
    com.wang.boot.pt.parttimes.partcategory.mapper: trace

#mybatis配置
mybatis:
  mapper-locations: classpath:mapper/*/*.xml

#分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

myproper:
  crosMapping: /**
  crosAllowed0rigins: http://127.0.0.1:8084, http://127.0.0.1:8085
  crosAllowedMethod: OPTIONS,GET,POST,DELETE,PUT,PATCH
